<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Bhbk</Authors>
    <Platforms>AnyCPU</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="3.7.414.4" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Bhbk.Lib.Common" Version="2025.4.16.1800" />
    <PackageReference Include="Google.Cloud.AIPlatform.V1" Version="3.54.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OllamaSharp" Version="5.4.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bhbk.Lib.Identity.MCP\Bhbk.Lib.Identity.MCP.csproj" />
  </ItemGroup>

</Project>
