
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Identity.sln --no-cache --verbosity minimal
    - dotnet build Bhbk.WebApi.Identity.sln --configuration Release --verbosity minimal /p:platform=x64

test:
  stage: test
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Identity.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.WebApi.Identity.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet test Bhbk.Lib.Identity.Domain.Tests\Bhbk.Lib.Identity.Domain.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Alert.Tests\Bhbk.WebApi.Alert.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Admin.Tests\Bhbk.WebApi.Identity.Admin.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Me.Tests\Bhbk.WebApi.Identity.Me.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Sts.Tests\Bhbk.WebApi.Identity.Sts.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set VERSION=2020.03.06.1930
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Identity.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.WebApi.Identity.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet pack Bhbk.Lib.Identity\Bhbk.Lib.Identity.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet publish Bhbk.Cli.Identity\Bhbk.Cli.Identity.csproj --output Bhbk.Cli.Identity\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Alert\Bhbk.WebApi.Alert.csproj --output Bhbk.WebApi.Alert\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Identity.Admin\Bhbk.WebApi.Identity.Admin.csproj --output Bhbk.WebApi.Identity.Admin\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Identity.Me\Bhbk.WebApi.Identity.Me.csproj --output Bhbk.WebApi.Identity.Me\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Identity.Sts\Bhbk.WebApi.Identity.Sts.csproj --output Bhbk.WebApi.Identity.Sts\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet octo pack --id=Bhbk.Cli.Identity --version=%VERSION% --basePath=Bhbk.Cli.Identity\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.WebApi.Alert --version=%VERSION% --basePath=Bhbk.WebApi.Alert\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Admin --version=%VERSION% --basePath=Bhbk.WebApi.Identity.Admin\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Me --version=%VERSION% --basePath=Bhbk.WebApi.Identity.Me\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Sts --version=%VERSION% --basePath=Bhbk.WebApi.Identity.Sts\bin\Release\netcoreapp3.1\publish --outFolder=.
    - cd ..
    - dotnet nuget push Arch(.NetCore)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - set VERSION=
