
variables:
  version: "2018.10.22.6314"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
  - debug
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - dotnet build "Bhbk.WebApi.Identity.sln" --configuration Release

test:
  stage: test
  only:
  - debug
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - dotnet build --verbosity quiet "Bhbk.WebApi.Identity.sln" --configuration Release
  - dotnet test "Bhbk.WebApi.Identity.Admin.Tests\Bhbk.WebApi.Identity.Admin.Tests.csproj" --configuration Release
  - dotnet test "Bhbk.WebApi.Identity.Me.Tests\Bhbk.WebApi.Identity.Me.Tests.csproj" --configuration Release
  - dotnet test "Bhbk.WebApi.Identity.Sts.Tests\Bhbk.WebApi.Identity.Sts.Tests.csproj" --configuration Release

deploy:
  stage: deploy
  only:
  - dummy
  script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - dotnet build --verbosity quiet "Bhbk.WebApi.Identity.sln" --configuration Release
  - dotnet pack "Bhbk.Lib.Identity\Bhbk.Lib.Identity.csproj" -p:PackageVersion=$version --output ".." --configuration Release -p:TargetFrameworks=netstandard2.0
  - dotnet publish "Bhbk.Cli.Identity\Bhbk.Cli.Identity.csproj" --output "bin\Release\netcoreapp2.2\publish" --configuration Release --framework netcoreapp2.2
  - dotnet publish "Bhbk.WebApi.Identity.Admin\Bhbk.WebApi.Identity.Admin.csproj" --output "bin\Release\netcoreapp2.2\publish" --configuration Release --framework netcoreapp2.2
  - dotnet publish "Bhbk.WebApi.Identity.Me\Bhbk.WebApi.Identity.Me.csproj" --output "bin\Release\netcoreapp2.2\publish" --configuration Release --framework netcoreapp2.2
  - dotnet publish "Bhbk.WebApi.Identity.Sts\Bhbk.WebApi.Identity.Sts.csproj" --output "bin\Release\netcoreapp2.2\publish" --configuration Release --framework netcoreapp2.2
  - octo pack --id="Bhbk.Cli.Identity" --version=$version --basePath="Bhbk.Cli.Identity\bin\Release\netcoreapp2.2\publish" --outFolder="."
  - octo pack --id="Bhbk.WebApi.Identity.Admin" --version=$version --basePath="Bhbk.WebApi.Identity.Admin\bin\Release\netcoreapp2.2\publish" --outFolder="."
  - octo pack --id="Bhbk.WebApi.Identity.Me" --version=$version --basePath="Bhbk.WebApi.Identity.Me\bin\Release\netcoreapp2.2\publish" --outFolder="."
  - octo pack --id="Bhbk.WebApi.Identity.Sts" --version=$version --basePath="Bhbk.WebApi.Identity.Sts\bin\Release\netcoreapp2.2\publish" --outFolder="."
  - dotnet nuget push *.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
