
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
    - powershell -command "& { if (test-path ..\.node_modules-x9et3y6s) { move-item ..\.node_modules-x9et3y6s .\node_modules } }"

after_script:
    - powershell -command "& { if (test-path .\node_modules) { move-item .\node_modules ..\.node_modules-x9et3y6s } }"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Identity.Data.EF6\Bhbk.Lib.Identity.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Identity.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Identity.sln --configuration Release --verbosity quiet
    - popd
    - pushd Arch(Typescript)\Bhbk.WebUi.Identity
    - call "%PROGRAMFILES%\nodejs\npm" config set registry https://registry.npmjs.org/
    - call "%PROGRAMFILES%\nodejs\npm" prune 
    - call "%PROGRAMFILES%\nodejs\npm" cache verify
    - call "%PROGRAMFILES%\nodejs\npm" install --silent
    - call "%APPDATA%\npm\ng" build --prod --base-href /ui/identity/ --no-progress
    - popd

test:
  stage: test
  only:
    - dummy
  script:
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Identity.Data.EF6\Bhbk.Lib.Identity.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Identity.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Identity.sln --configuration Release --verbosity quiet
    - dotnet test Bhbk.Lib.Identity.Data.EF6.Tests\Bhbk.Lib.Identity.Data.EF6.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Lib.Identity.Data.EFCore.Tests\Bhbk.Lib.Identity.Data.EFCore.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Alert.Tests\Bhbk.WebApi.Alert.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Admin.Tests\Bhbk.WebApi.Identity.Admin.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Me.Tests\Bhbk.WebApi.Identity.Me.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Identity.Sts.Tests\Bhbk.WebApi.Identity.Sts.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - popd
    - pushd Arch(Typescript)\Bhbk.WebUi.Identity
    - call "%APPDATA%\npm\ng" test --browsers ChromeHeadless --watch=false
    - popd

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set IDENTITYVERSION=2020.11.27.2100
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Identity.Data.EF6\Bhbk.Lib.Identity.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Identity.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Identity.sln --configuration Release --verbosity quiet
    - dotnet pack Bhbk.Lib.Identity\Bhbk.Lib.Identity.csproj -p:PackageVersion=%IDENTITYVERSION% --output . --configuration Release
    - dotnet publish Bhbk.Cli.Alert\Bhbk.Cli.Alert.csproj --output Bhbk.Cli.Alert\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.Cli.Identity\Bhbk.Cli.Identity.csproj --output Bhbk.Cli.Identity\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.WebApi.Alert\Bhbk.WebApi.Alert.csproj --output Bhbk.WebApi.Alert\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.WebApi.Identity.Admin\Bhbk.WebApi.Identity.Admin.csproj --output Bhbk.WebApi.Identity.Admin\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.WebApi.Identity.Me\Bhbk.WebApi.Identity.Me.csproj --output Bhbk.WebApi.Identity.Me\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.WebApi.Identity.Sts\Bhbk.WebApi.Identity.Sts.csproj --output Bhbk.WebApi.Identity.Sts\bin\Release\net5.0\publish\ --configuration Release
    - dotnet octo pack --id=Bhbk.Cli.Alert --version=%IDENTITYVERSION% --basePath=Bhbk.Cli.Alert\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.Cli.Identity --version=%IDENTITYVERSION% --basePath=Bhbk.Cli.Identity\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Alert --version=%IDENTITYVERSION% --basePath=Bhbk.WebApi.Alert\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Admin --version=%IDENTITYVERSION% --basePath=Bhbk.WebApi.Identity.Admin\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Me --version=%IDENTITYVERSION% --basePath=Bhbk.WebApi.Identity.Me\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Identity.Sts --version=%IDENTITYVERSION% --basePath=Bhbk.WebApi.Identity.Sts\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - popd
    - pushd Arch(Typescript)
    - dotnet octo pack --id=Bhbk.WebUi.Identity --version=%IDENTITYVERSION% --basePath=Bhbk.WebUi.Identity\dist --outFolder=. --overwrite
    - popd
    - dotnet nuget push Arch(.NetCore)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - dotnet nuget push Arch(Typescript)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - set IDENTITYVERSION=
