CREATE TABLE [dbo].[TCodes] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [IssuerId]     UNIQUEIDENTIFIER NOT NULL,
    [ClientId]     UNIQUEIDENTIFIER NULL,
    [UserId]       UNIQUEIDENTIFIER NOT NULL,
    [CodeValue]    NVARCHAR (MAX)   NOT NULL,
    [CodeType]     NVARCHAR (64)    NOT NULL,
    [ValidFromUtc] NVARCHAR (64)    NOT NULL,
    [ValidToUtc]   DATETIME2 (7)    NOT NULL,
    [Created]      DATETIME2 (7)    NOT NULL,
    CONSTRAINT [PK_UserTokens] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TCodes_TClients] FOREIGN KEY ([ClientId]) REFERENCES [dbo].[TClients] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_TCodes_TIssuers] FOREIGN KEY ([IssuerId]) REFERENCES [dbo].[TIssuers] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_TCodes_UserID] FOREIGN KEY ([UserId]) REFERENCES [dbo].[TUsers] ([Id]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_UserTokens]
    ON [dbo].[TCodes]([Id] ASC);

