//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models_DIRECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Refreshes
    {
        public System.Guid Id { get; set; }
        public System.Guid IssuerId { get; set; }
        public Nullable<System.Guid> AudienceId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string RefreshValue { get; set; }
        public string RefreshType { get; set; }
        public System.DateTime ValidFromUtc { get; set; }
        public System.DateTime ValidToUtc { get; set; }
        public System.DateTime IssuedUtc { get; set; }
    
        public virtual tbl_Audiences tbl_Audiences { get; set; }
        public virtual tbl_Issuers tbl_Issuers { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
