//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models_DIRECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserClaim
    {
        public System.Guid UserId { get; set; }
        public System.Guid ClaimId { get; set; }
        public Nullable<System.Guid> ActorId { get; set; }
        public bool IsDeletable { get; set; }
        public System.DateTimeOffset CreatedUtc { get; set; }
    
        public virtual tbl_Claim tbl_Claim { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
