//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models_DIRECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MOTDs
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Quote { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Tags { get; set; }
        public Nullable<int> Length { get; set; }
        public string Background { get; set; }
    }
}
