//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models_DIRECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Audience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Audience()
        {
            this.tbl_Activity = new HashSet<tbl_Activity>();
            this.tbl_AudienceRole = new HashSet<tbl_AudienceRole>();
            this.tbl_Refresh = new HashSet<tbl_Refresh>();
            this.tbl_Role = new HashSet<tbl_Role>();
            this.tbl_Setting = new HashSet<tbl_Setting>();
            this.tbl_State = new HashSet<tbl_State>();
            this.tbl_Url = new HashSet<tbl_Url>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid IssuerId { get; set; }
        public Nullable<System.Guid> ActorId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PasswordHashPBKDF2 { get; set; }
        public string PasswordHashSHA256 { get; set; }
        public string SecurityStamp { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeletable { get; set; }
        public int AccessFailedCount { get; set; }
        public int AccessSuccessCount { get; set; }
        public Nullable<System.DateTimeOffset> LockoutEndUtc { get; set; }
        public Nullable<System.DateTimeOffset> LastLoginSuccessUtc { get; set; }
        public Nullable<System.DateTimeOffset> LastLoginFailureUtc { get; set; }
        public System.DateTimeOffset CreatedUtc { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Activity> tbl_Activity { get; set; }
        public virtual tbl_Issuer tbl_Issuer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AudienceRole> tbl_AudienceRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Refresh> tbl_Refresh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Role> tbl_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Setting> tbl_Setting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_State> tbl_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Url> tbl_Url { get; set; }
    }
}
