//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data_EF6.Models_TSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_EmailQueue
    {
        public System.Guid Id { get; set; }
        public string FromEmail { get; set; }
        public string FromDisplay { get; set; }
        public string ToEmail { get; set; }
        public string ToDisplay { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public System.DateTimeOffset CreatedUtc { get; set; }
        public System.DateTimeOffset SendAtUtc { get; set; }
        public Nullable<System.DateTimeOffset> DeliveredUtc { get; set; }
    }
}
