//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data_EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_State
    {
        public System.Guid Id { get; set; }
        public System.Guid IssuerId { get; set; }
        public Nullable<System.Guid> AudienceId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string StateValue { get; set; }
        public string StateType { get; set; }
        public Nullable<bool> StateDecision { get; set; }
        public bool StateConsume { get; set; }
        public System.DateTimeOffset ValidFromUtc { get; set; }
        public System.DateTimeOffset ValidToUtc { get; set; }
        public System.DateTimeOffset IssuedUtc { get; set; }
        public System.DateTimeOffset LastPollingUtc { get; set; }
    
        public virtual E_Audience Audience { get; set; }
        public virtual E_Issuer Issuer { get; set; }
        public virtual E_User User { get; set; }
    }
}
