//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data_EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_MOTD
    {
        public System.Guid Id { get; set; }
        public string Author { get; set; }
        public string Quote { get; set; }
        public string TssId { get; set; }
        public string TssTitle { get; set; }
        public string TssCategory { get; set; }
        public Nullable<int> TssLength { get; set; }
        public Nullable<System.DateTime> TssDate { get; set; }
        public string TssTags { get; set; }
        public string TssBackground { get; set; }
    }
}
