//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdentityEntities : DbContext
    {
        public IdentityEntities()
            : base("name=IdentityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uvw_Activity> uvw_Activity { get; set; }
        public virtual DbSet<uvw_Audience> uvw_Audience { get; set; }
        public virtual DbSet<uvw_AudienceRole> uvw_AudienceRole { get; set; }
        public virtual DbSet<uvw_Claim> uvw_Claim { get; set; }
        public virtual DbSet<uvw_Issuer> uvw_Issuer { get; set; }
        public virtual DbSet<uvw_Login> uvw_Login { get; set; }
        public virtual DbSet<uvw_MOTD> uvw_MOTD { get; set; }
        public virtual DbSet<uvw_QueueEmail> uvw_QueueEmail { get; set; }
        public virtual DbSet<uvw_QueueText> uvw_QueueText { get; set; }
        public virtual DbSet<uvw_Refresh> uvw_Refresh { get; set; }
        public virtual DbSet<uvw_Role> uvw_Role { get; set; }
        public virtual DbSet<uvw_Setting> uvw_Setting { get; set; }
        public virtual DbSet<uvw_State> uvw_State { get; set; }
        public virtual DbSet<uvw_Url> uvw_Url { get; set; }
        public virtual DbSet<uvw_User> uvw_User { get; set; }
    }
}
