//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Data.EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_Setting
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IssuerId { get; set; }
        public Nullable<System.Guid> AudienceId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValue { get; set; }
        public System.DateTime Created { get; set; }
        public bool Immutable { get; set; }
    }
}
