//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Core.Identity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public System.Guid InitiatorID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> VenueID { get; set; }
        public string Action { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Column { get; set; }
        public string Table { get; set; }
        public string ValueBefore { get; set; }
        public string ValueAfter { get; set; }
    
        public virtual User ActivityInitiator { get; set; }
        public virtual User ActivityUser { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
