//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserToken
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid AudienceId { get; set; }
        public string ProtectedTicket { get; set; }
        public System.DateTime IssuedUtc { get; set; }
        public System.DateTime ExpiresUtc { get; set; }
    
        public virtual AppAudience Audiences { get; set; }
        public virtual AppUser Users { get; set; }
    }
}
