//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserProvider
    {
        public System.Guid ProviderId { get; set; }
        public System.Guid UserId { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime Created { get; set; }
        public bool Immutable { get; set; }
    
        public virtual AppProvider Providers { get; set; }
        public virtual AppUser Users { get; set; }
    }
}
