//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Identity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserClaim
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
        public string ClaimValueType { get; set; }
        public string Issuer { get; set; }
        public string OriginalIssuer { get; set; }
        public string Subject { get; set; }
        public System.DateTime Created { get; set; }
        public bool Immutable { get; set; }
    
        public virtual AppUser Users { get; set; }
    }
}
